name: Fetch News Data  # 뉴스 데이터 수집

on:
  schedule:
    - cron: '*/20 * * * *'  # 20분마다 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능하게 추가 (옵션)

jobs:
  run_script:
    runs-on: ubuntu-latest  # 최신 Ubuntu 환경에서 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 리포지토리 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v2  # Python 환경 설정
        with:
          python-version: '3.9'  # 원하는 Python 버전 설정
      - name: 최신 빌드 도구 설치
        run: | 
          pip install --upgrade setuptools wheel  # 최신 빌드 도구 업그레이드
    

      - name: package install
        run: |  # 웹 크롤링 및 DB 저장 라이브러리 설치
          pip install beautifulsoup4
          pip install requests
          pip install numpy==1.21.2  # gensim 3.8.3과 호환되는 numpy 버전
          pip install gensim==3.8.3  # gensim 3.8.3 버전 설치
          pip install flask  # flask 패키지 설치
          pip install selenium  # selenium 패키지 설치
          pip install scipy==1.7.3  # scipy 버전 1.7.3으로 고정

      - name: Run script
        run: |
          python new_script.py  # new_script.py 실행
      
      - name: change push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-action@github.com"
          if ls *.db 1> /dev/null 2>&1; then
            git add *.db  # .db 파일이 있을 경우에만 추가
            git commit -m "Update news data (auto)" || echo "No changes to commit"
            git push
          else
            echo "No .db files to commit"
          fi
